name: Discord Notification

on:
  workflow_run:
    workflows: ["Deploy to Production"]
    types:
      - completed

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "Un nouveau push a été effectué sur la branche main ! 🚀"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}